[package]
name = "part_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
graph = "0.3.1"
grid = "0.15.0"
ordered-float = "4.5.0"
pathfinding = "4.12.0"
priority-queue = "2.1.1"
